' +======================================================================+
' | Procedure no 404 / Distance computation from ground speed
' | Generated by Cassiopée for airline GFA / A321NEO 251N / reference 103767
' | Beware: the code has been generated for this specific configuration
' | Please do not edit by hand
' +======================================================================+

' Compute cumulative distance from the beginning of the analysis
'---------------------------------------------------------------

' init sum at the beginning of the analysis
If (FLIGHT_INPUT = 1)
    If (START_ANALYSIS = 1)
        DIST0 = 0
    End If
Else
    If (Not _flight_started)
        _flight_started = True
        DIST0 = 0
    End If
End If

Dim _range_max As Single = 700 'maximum value range
Dim _range_min As Single = 0 'minimum value range

If (GS >= _range_min AndAlso GS <= _range_max AndAlso Abs(GS-GS(-1)) < 100)
    ' sum distance
    DIST0 = DIST0 + GS / 3600 
End If
