' +======================================================================+
' | Procedure no 0 / Date initialisation
' | Generated by Cassiopée for airline GFA / A321NEO 251N / reference 103767
' | Beware: the code has been generated for this specific configuration
' | Please do not edit by hand
' +======================================================================+

' Compute current date
' ====================

' get current date
_date = PcDate()

' extract current century
CENT_CURR = _date/1000000

' extract current year
_date = _date - CENT_CURR*1000000
YEAR_CURR = _date/10000

' extract current month
_date = _date - YEAR_CURR*10000
MONTH_CURR = _date/100

' extract current current day
DAY_CURR = _date - MONTH_CURR*100

' Handle date initialization
' (media date Or current date - 9 years)
' ======================================
' No date initialisation in case of replay
DATE_PARAM = (CENT_CURR*100 + YEAR_CURR - 9)*10000 + MONTH_CURR*100 + DAY_CURR
TIME = PCTime()
