' +======================================================================+
' | Procedure no 10 / First pass parameters declaration
' | Generated by Cassiopée for airline GFA / A321NEO 251N / reference 103767
' | Beware: the code has been generated for this specific configuration
' | Please do not edit by hand
' +======================================================================+

' for origin and destination computation
Framework.StateManager.Register(ORIGIN, "TouchDown")
Framework.StateManager.Register(RUNWAY_TO, "TouchDown")
Framework.StateManager.Register(HEAD_TAKE_OFF, "TouchDown")
Framework.StateManager.Register(DESTINATION, "TouchDown")
Framework.StateManager.Register(RUNWAY_LD, "TouchDown")

' for orgin/destination distance and altitude memorisation
Framework.StateManager.Register(ARP_DIST_ORIG, "TouchDown")
Framework.StateManager.Register(ARP_HEIGH_ORIG, "TouchDown")
Framework.StateManager.Register(ARP_DIST_TRANS, "TouchDown")
Framework.StateManager.Register(ARP_HEIGH_TRANS, "TouchDown")
Framework.StateManager.Register(ARP_DIST_DEST, "TouchDown")
Framework.StateManager.Register(ARP_HEIGH_DEST, "TouchDown")

' instants for radio altitude invalidity period
Framework.StateManager.Register(RALT_INV_START_T, "TouchDown")
Framework.StateManager.Register(RALT_INV_STOP_T, "TouchDown")
Framework.StateManager.Register(TAKEOFF_POWER_T, "TouchDown")
Framework.StateManager.Register(ROTATION_STA_T, "TouchDown")
' instants for flight phases
Framework.StateManager.Register(TOC_T, "TouchDown")
Framework.StateManager.Register(TOD_T, "TouchDown")
Framework.StateManager.Register(FLARE_STA_T, "TouchDown")
Framework.StateManager.Register(GO_AROUND_1_T, "TouchDown")
Framework.StateManager.Register(GO_AROUND_2_T, "TouchDown")
Framework.StateManager.Register(GO_AROUND_3_T, "TouchDown")
Framework.StateManager.Register(GO_AROUND_4_T, "TouchDown")
Framework.StateManager.Register(GO_AROUND_5_T, "TouchDown")
Framework.StateManager.Register(AP_VALID, "TouchDown")

' validity of ILS
Framework.StateManager.Register(GLIDE_DEV1_VALID, "TouchDown")
Framework.StateManager.Register(GLIDE_DEV2_VALID, "TouchDown")
Framework.StateManager.Register(FOB_VALID, "TouchDown")
' configuration at landing
Framework.StateManager.Register(TOUCH_DOWN_CONF, "TouchDown")
' flaps at landing
Framework.StateManager.Register(TOUCH_DOWN_FLAPS, "TouchDown")

Framework.StateManager.Register(FIN_APP_AXIS, "TouchDown")
' glide used memorisation
Framework.StateManager.Register(GLS_USED, "TouchDown")

Framework.StateManager.Register(LEVEL_OFF_1_T, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_1_ALT, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_2_T, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_2_ALT, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_3_T, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_3_ALT, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_4_T, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_4_ALT, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_5_T, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_5_ALT, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_6_T, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_6_ALT, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_7_T, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_7_ALT, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_8_T, "TouchDown")
Framework.StateManager.Register(LEVEL_OFF_8_ALT, "TouchDown")

Framework.StateManager.Register(TOTAL_FU_CF, "TouchDown")

Framework.StateManager.Register(TOUCH_DOWN_T, "TouchDown")

Framework.StateManager.Register(LIFT_OFF_T, "TouchDown")
