' +======================================================================+
' | Procedure no 102 / Radio altitude first pass correction
' | Generated by Cassiopée for airline GFA / A321NEO 251N / reference 103767
' | Beware: the code has been generated for this specific configuration
' | Please do not edit by hand
' +======================================================================+

' RADIO ALTITUDE correction for all sources
'------------------------------------------

' First pass only (no on ground correction for ralt in first pass)

' Correction for source 1 (RALT1)
'---------------------------------------------

' Default value = recorded value
RALT1_C = RALT1

' Avoid out of operationnal range values, keep previous corrected value in this case
If (RALT1_C > 2500 OrElse RALT1_C < 0)
    RALT1_C = RALT1_C(-0.25)
End If

' Ground the signal to 0  when ac is too slow
If (_need_reset OrElse START_ANALYSIS = 1)
    RALT1_C = 0
End If

' Correction for source 2 (RALT2)
'---------------------------------------------

' Default value = recorded value
RALT2_C = RALT2

' Avoid out of operationnal range values, keep previous corrected value in this case
If (RALT2_C > 2500 OrElse RALT2_C < 0)
    RALT2_C = RALT2_C(-0.25)
End If

' Ground the signal to 0  when ac is too slow
If (_need_reset OrElse START_ANALYSIS = 1)
    RALT2_C = 0
End If

' Detect when ac obviously doesn't go fast enough (below 80 kts during 30 secs)
'-------------------------------------------------------------------------------

If (GS <= 80).During(30)
    _need_reset = True
Else
    _need_reset = False
End If