' +======================================================================+
' | Procedure no 104 / Latitude-longitude first pass correction
' | Generated by Cassiopée for airline GFA / A321NEO 251N / reference 103767
' | Beware: the code has been generated for this specific configuration
' | Please do not edit by hand
' +======================================================================+

' compute thresholds at the start of analysis
If (Not _flight_started)
    _flight_started = True
    
    _lat_p4 = LATP
    _lat_p3 = LATP
    _lat_p2 = LATP
    _lat_p1 = LATP
    _lat_p0 = LATP
 
    _lon_p4 = LONP
    _lon_p3 = LONP
    _lon_p2 = LONP
    _lon_p1 = LONP
    _lon_p0 = LONP
 
End If

' Detection of first move to allow the use of C_FINE_COARSE afterwards
' Otherwise the C_FINE_COARSE applies inappropriately at initialization because offset is overshot
If (Not _has_moved AndAlso GS_C(-1) > 5)
  _has_moved = True
End If

_lat_p0  = LATP
_lon_p0 = LONP

If (ABS(LATPC)<90)
' Filter mode activated

  If (ABS(_lat_p3 - _lat_p4) < 0.025 AndAlso ABS(_lat_p2 - _lat_p3) < 0.025 AndAlso ABS(_lat_p1 - _lat_p2) < 0.025 AndAlso ABS(_lat_p0 - _lat_p1) < 0.025)
    _lat_7 = (_lat_p4 + _lat_p3 + _lat_p2 + _lat_p1 + _lat_p0)/5 
  Else
    _lat_7 = _lat_p2
  End If
Else
    _lat_7 = _lat_p2
End If

If (ABS(LONPC)<180)
' Filter mode activated
  If (ABS(_lon_p3 - _lon_p4) < 0.025 AndAlso ABS(_lon_p2 - _lon_p3) < 0.025 AndAlso ABS(_lon_p1 - _lon_p2) < 0.025 AndAlso ABS(_lon_p0 - _lon_p1) < 0.025)
    _lon_7 = (_lon_p4 + _lon_p3 + _lon_p2 + _lon_p1 + _lon_p0)/5 
  Else
    _lon_7 = _lon_p2
  End If
Else
    _lon_7 = _lon_p2
End If

LATPC = _lat_7
LONPC = _lon_7

_lat_p4 = _lat_p3
_lat_p3 = _lat_p2
_lat_p2 = _lat_p1
_lat_p1 = _lat_p0
_lon_p4 = _lon_p3
_lon_p3 = _lon_p2
_lon_p2 = _lon_p1
_lon_p1 = _lon_p0