' +======================================================================+
' | Procedure no 106 / Fuel flow first pass correction
' | Generated by Cassiopée for airline GFA / A321NEO 251N / reference 103767
' | Beware: the code has been generated for this specific configuration
' | Please do not edit by hand
' +======================================================================+

If (FlightStart)
    _range_max = 8000 'operational maximum value
    _range_min = 0 'operational minimum value
    _gap_thresh = _range_max/(10*1)  'threshold used to detect a gap
    _gapsimi_ratio=0.2 'ratio used for the automatic computation of gap 'simi'
    
    _p51=FF1 
    _p41=FF1 
    _p31=FF1 
    _p21=FF1 
    _p11=FF1 
    _p52=FF2 
    _p42=FF2 
    _p32=FF2 
    _p22=FF2 
    _p12=FF2 
End If

_t01=FF1 
_t02=FF2 

'--------------------------------------
' Look for 'out of range value' pattern for engine 1
If (_t01 < _range_min OrElse _t01 > _range_max)
    _out_of_range1 = 1
End If
' Look for 'out of range value' pattern for engine 2
If (_t02 < _range_min OrElse _t02 > _range_max)
    _out_of_range2 = 1
End If

'--------------------------------------
' Look for 'gap' pattern for engine 1
'check that the gap is important enough between the two main samples
_delta23 = ABS(_p21-_p11)
If (_delta23 >= _gap_thresh)
    _auto_simi = _gapsimi_ratio * _delta23 'automatic 'simi' computation
    'check that there are two 'plates' before and after the gap
    _delta12 = ABS(_p31-_p21)
    If (_delta12 <= _auto_simi)
        _delta34 = ABS(_p11-_t01)
        If (_delta34 <= _auto_simi)
            _gap1 = 1
        End If
    End If
End If
' Look for 'gap' pattern for engine 2
'check that the gap is important enough between the two main samples
_delta23 = ABS(_p22-_p12)
If (_delta23 >= _gap_thresh)
    _auto_simi = _gapsimi_ratio * _delta23 'automatic 'simi' computation
    'check that there are two 'plates' before and after the gap
    _delta12 = ABS(_p32-_p22)
    If (_delta12 <= _auto_simi)
        _delta34 = ABS(_p12-_t02)
        If (_delta34 <= _auto_simi)
            _gap2 = 1
        End If
    End If
End If

'--------------------------------------
' Look for 'spike' pattern for engine 1
'check that the gap is important enough between the two main samples
_delta23 = ABS(_p31-_p21)
If (_delta23 >= _gap_thresh)
    _auto_simi = _gapsimi_ratio * _delta23 'automatic 'simi' computation
    'check that there are two 'plates' before and after the gap
    _delta12 = ABS(_p41-_p31)
    If (_delta12 <= _auto_simi)
        _delta45 = ABS(_p11-_t01)
        If (_delta45 <= _auto_simi)  
            _delta24 = ABS(_p31-_p11)
            If (_delta24 <= _auto_simi)
                _spike1 = 1
            End If
        End If
    End If
End If
' Look for 'spike' pattern for engine 2
'check that the gap is important enough between the two main samples
_delta23 = ABS(_p32-_p22)
If (_delta23 >= _gap_thresh)
    _auto_simi = _gapsimi_ratio * _delta23 'automatic 'simi' computation
    'check that there are two 'plates' before and after the gap
    _delta12 = ABS(_p42-_p32)
    If (_delta12 <= _auto_simi)
        _delta45 = ABS(_p12-_t02)
        If (_delta45 <= _auto_simi)  
            _delta24 = ABS(_p32-_p12)
            If (_delta24 <= _auto_simi)
                _spike2 = 1
            End If
        End If
    End If
End If

'-------------------------------------------------------
' Look for 'no recordings' pattern for engine 1
'check for a pattern of no recordings
If (_t01=0 AndAlso _p11 <> 0)
    _delta12 = ABS(_p11-_t01)
    If (_delta12 > _gap_thresh AndAlso _p21=0)  '3 points pattern
        _no_recordings1=2
    Else
        _delta13 = ABS(_t01-_p21)
        If (_delta12 > _gap_thresh OrElse _delta13 > _gap_thresh)
            If (_p31=0)  '4 points pattern
                _no_recordings1=3
            Else
                If (_p41=0)  '5 points pattern
                    _no_recordings1=4
                Else
                    If (_p11=_p21 AndAlso _p11=_p31 AndAlso _p11=_p41)
                        If (_p51=0)  '6 points pattern
                            _no_recordings1=5
						End If
                     End If
                End If
            End If
        End If
    End If
End If
' Look for 'no recordings' pattern for engine 2
'check for a pattern of no recordings
If (_t02=0 AndAlso _p12 <> 0)
    _delta12 = ABS(_p12-_t02)
    If (_delta12 > _gap_thresh AndAlso _p22=0)  '3 points pattern
        _no_recordings2=2
    Else
        _delta13 = ABS(_t02-_p22)
        If (_delta12 > _gap_thresh OrElse _delta13 > _gap_thresh)
            If (_p32=0)  '4 points pattern
                _no_recordings2=3
            Else
                If (_p42=0)  '5 points pattern
                    _no_recordings2=4
                Else
                    If (_p12=_p22 AndAlso _p12=_p32 AndAlso _p12=_p42)
                        If (_p52=0)  '6 points pattern
                            _no_recordings2=5
						End If
                     End If
                End If
            End If
        End If
    End If
End If

If (_out_of_range_T1 <> 0 OrElse _gap_T1 <> 0 OrElse _spike_T1 <> 0  OrElse _no_recordings_T1 <> 0 ) Then
    _invalid_T1 = Integer.MaxValue
    If (_out_of_range_T1 <> 0)
        _invalid_T1 = Min(_invalid_T1,_out_of_range_T1)
    End If
    If (_gap_T1 <> 0)
        _invalid_T1 = Min(_invalid_T1,_gap_T1)
    End If
    If (_spike_T1 <> 0)
        _invalid_T1 = Min(_invalid_T1,_spike_T1)
    End If
    If (_no_recordings_T1 <> 0)
        _invalid_T1 = Min(_invalid_T1,_no_recordings_T1)
    End If
    ParameterValid(FF1, False, _invalid_T1)

End If
If (_out_of_range1 = 0 AndAlso _gap1 = 0 AndAlso _spike1 = 0 AndAlso _no_recordings1 = 0).During(10)
	If (_spike_T1 <> 0)
       _valid1 = 11
    End If
    If (_gap_T1 <> 0 OrElse _out_of_range_T1 <> 0 OrElse _no_recordings_T1 <> 0)
        _valid1 = 5
    End If
    If (_out_of_range_T1 <> 0 OrElse _gap_T1 <> 0 Or _spike_T1 <> 0 OrElse _no_recordings_T1 <> 0) Then
        ParameterValid(FF1, True,T-_valid1*RATE)
        _out_of_range_T1 = 0
        _gap_T1 = 0
        _spike_T1 = 0
        _no_recordings_T1 = 0
    End If
End If
If (_out_of_range1 > 0)
    If (_out_of_range_T1 = 0)
        _out_of_range_T1 = T
    End If
    _out_of_range1 -= 1
End If
If (_gap1 > 0)
    If (_gap_T1 = 0)
        _gap_T1 = T-2*RATE 
    End If
    _gap1 -= 1
End If
If (_spike1 > 0)
    If (_spike_T1 = 0)
        _spike_T1 = T-2*RATE 
    End If
    _spike1 -= 1
End If
If (_no_recordings1 > 0)
    If (_no_recordings_T1 = 0)
        _no_recordings_T1 = T-_no_recordings1*RATE 
    End If
    _no_recordings1 -= 1
End If
If (_out_of_range_T2 <> 0 OrElse _gap_T2 <> 0 OrElse _spike_T2 <> 0  OrElse _no_recordings_T2 <> 0 ) Then
    _invalid_T2 = Integer.MaxValue
    If (_out_of_range_T2 <> 0)
        _invalid_T2 = Min(_invalid_T2,_out_of_range_T2)
    End If
    If (_gap_T2 <> 0)
        _invalid_T2 = Min(_invalid_T2,_gap_T2)
    End If
    If (_spike_T2 <> 0)
        _invalid_T2 = Min(_invalid_T2,_spike_T2)
    End If
    If (_no_recordings_T2 <> 0)
        _invalid_T2 = Min(_invalid_T2,_no_recordings_T2)
    End If
    ParameterValid(FF2, False, _invalid_T2)

End If
If (_out_of_range2 = 0 AndAlso _gap2 = 0 AndAlso _spike2 = 0 AndAlso _no_recordings2 = 0).During(10)
	If (_spike_T2 <> 0)
       _valid2 = 11
    End If
    If (_gap_T2 <> 0 OrElse _out_of_range_T2 <> 0 OrElse _no_recordings_T2 <> 0)
        _valid2 = 5
    End If
    If (_out_of_range_T2 <> 0 OrElse _gap_T2 <> 0 Or _spike_T2 <> 0 OrElse _no_recordings_T2 <> 0) Then
        ParameterValid(FF2, True,T-_valid2*RATE)
        _out_of_range_T2 = 0
        _gap_T2 = 0
        _spike_T2 = 0
        _no_recordings_T2 = 0
    End If
End If
If (_out_of_range2 > 0)
    If (_out_of_range_T2 = 0)
        _out_of_range_T2 = T
    End If
    _out_of_range2 -= 1
End If
If (_gap2 > 0)
    If (_gap_T2 = 0)
        _gap_T2 = T-2*RATE 
    End If
    _gap2 -= 1
End If
If (_spike2 > 0)
    If (_spike_T2 = 0)
        _spike_T2 = T-2*RATE 
    End If
    _spike2 -= 1
End If
If (_no_recordings2 > 0)
    If (_no_recordings_T2 = 0)
        _no_recordings_T2 = T-_no_recordings2*RATE 
    End If
    _no_recordings2 -= 1
End If

' -------------------------------
' Assignment of corrected variable
FF1_C = _t01
FF2_C = _t02

'-------------------------------------------------------------------------
'Prepare next iteration by updating gliding window by shifting all samples
' p = past
_p51=_p41
_p41=_p31
_p31=_p21
_p21=_p11
_p11=_t01

_p52=_p42
_p42=_p32
_p32=_p22
_p22=_p12
_p12=_t02

