' +======================================================================+
' | Procedure no 110 / Vertical acceleration first pass correction
' | Generated by Cassiopée for airline GFA / A321NEO 251N / reference 103767
' | Beware: the code has been generated for this specific configuration
' | Please do not edit by hand
' +======================================================================+

If (FlightStart)
    _range_max = 3 'operational maximum value
    _range_min = -2 'operational minimum value
    _gap_thresh = 0.6  'threshold used to detect a gap
    _gapsimi_ratio=0.2 'ratio used for the automatic computation of gap 'simi'
    
    _p5=VRTG 
    _p4=VRTG 
    _p3=VRTG 
    _p2=VRTG 
    _p1=VRTG 
End If

_t0=VRTG 

'--------------------------------------
' Look for 'out of range value' pattern
If (_t0 < _range_min OrElse _t0 > _range_max)
    _out_of_range = 1
End If

'--------------------------------------
' Look for 'gap' pattern
'check that the gap is important enough between the two main samples
_delta23 = ABS(_p2-_p1)
If (_delta23 >= _gap_thresh)
    _auto_simi = _gapsimi_ratio * _delta23 'automatic 'simi' computation
    'check that there are two 'plates' before and after the gap
    _delta12 = ABS(_p3-_p2)
    If (_delta12 <= _auto_simi)
        _delta34 = ABS(_p1-_t0)
        If (_delta34 <= _auto_simi)
            _gap = 1
        End If
    End If
End If

'--------------------------------------
' Look for 'spike' pattern
'check that the gap is important enough between the two main samples
_delta23 = ABS(_p3-_p2)
If (_delta23 >= _gap_thresh)
    _auto_simi = _gapsimi_ratio * _delta23 'automatic 'simi' computation
    'check that there are two 'plates' before and after the gap
    _delta12 = ABS(_p4-_p3)
    If (_delta12 <= _auto_simi)
        _delta45 = ABS(_p1-_t0)
        If (_delta45 <= _auto_simi)  
            _delta24 = ABS(_p3-_p1)
            If (_delta24 <= _auto_simi)
                _spike = 1
            End If
        End If
    End If
End If

'-------------------------------------------------------
' Look for 'no recordings' pattern
'check for a pattern of no recordings
If (_t0=0 AndAlso _p1 <> 0)
    _delta12 = ABS(_p1-_t0)
    If (_delta12 > _gap_thresh AndAlso _p2=0)  '3 points pattern
        _no_recordings=2
    Else
        _delta13 = ABS(_t0-_p2)
        If (_delta12 > _gap_thresh OrElse _delta13 > _gap_thresh)
            If (_p3=0)  '4 points pattern
                _no_recordings=3
            Else
                If (_p4=0)  '5 points pattern
                    _no_recordings=4
                Else
                    If (_p1=_p2 AndAlso _p1=_p3 AndAlso _p1=_p4)
                        If (_p5=0)  '6 points pattern
                            _no_recordings=5
						End If
                     End If
                End If
            End If
        End If
    End If
End If

If (_out_of_range_T <> 0 OrElse _gap_T <> 0 OrElse _spike_T <> 0  OrElse _no_recordings_T <> 0 ) Then
    _invalid_T = Integer.MaxValue
    If (_out_of_range_T <> 0)
        _invalid_T = Min(_invalid_T,_out_of_range_T)
    End If
    If (_gap_T <> 0)
        _invalid_T = Min(_invalid_T,_gap_T)
    End If
    If (_spike_T <> 0)
        _invalid_T = Min(_invalid_T,_spike_T)
    End If
    If (_no_recordings_T <> 0)
        _invalid_T = Min(_invalid_T,_no_recordings_T)
    End If
    ParameterValid(VRTG, False, _invalid_T)

End If
If (_out_of_range = 0 AndAlso _gap = 0 AndAlso _spike = 0 AndAlso _no_recordings = 0).During(10)
	If (_spike_T <> 0)
       _valid = 11
    End If
    If (_gap_T <> 0 OrElse _out_of_range_T <> 0 OrElse _no_recordings_T <> 0)
        _valid = 5
    End If
    If (_out_of_range_T <> 0 OrElse _gap_T <> 0 Or _spike_T <> 0 OrElse _no_recordings_T <> 0) Then
        ParameterValid(VRTG, True,T-_valid*RATE/8)
        _out_of_range_T = 0
        _gap_T = 0
        _spike_T = 0
        _no_recordings_T = 0
    End If
End If
If (_out_of_range > 0)
    If (_out_of_range_T = 0)
        _out_of_range_T = T
    End If
    _out_of_range -= 1
End If
If (_gap > 0)
    If (_gap_T = 0)
        _gap_T = T-2*RATE/8 
    End If
    _gap -= 1
End If
If (_spike > 0)
    If (_spike_T = 0)
        _spike_T = T-2*RATE/8 
    End If
    _spike -= 1
End If
If (_no_recordings > 0)
    If (_no_recordings_T = 0)
        _no_recordings_T = T-_no_recordings*RATE/8 
    End If
    _no_recordings -= 1
End If

' -------------------------------
' Assignment of corrected variable
VRTG_C = _t0

'-------------------------------------------------------------------------
'Prepare next iteration by updating gliding window by shifting all samples
' p = past
_p5=_p4
_p4=_p3
_p3=_p2
_p2=_p1
_p1=_t0

