' +======================================================================+
' | Procedure no 148 / Gross weight first pass correction
' | Generated by Cassiopée for airline GFA / A321NEO 251N / reference 103767
' | Beware: the code has been generated for this specific configuration
' | Please do not edit by hand
' +======================================================================+

If (FlightStart)
    _range_max = 105000 'operational maximum value
    _range_min = 35000 'operational minimum value
    
    _p5=GW 
    _p4=GW 
    _p3=GW 
    _p2=GW 
    _p1=GW 
End If

_t0=GW 

'--------------------------------------
' Look for 'out of range value' pattern
If (_t0 < _range_min OrElse _t0 > _range_max)
    _out_of_range = 1
End If

If (_out_of_range_T <> 0) Then
    _invalid_T = Integer.MaxValue
    If (_out_of_range_T <> 0)
        _invalid_T = Min(_invalid_T,_out_of_range_T)
    End If
    ParameterValid(GW, False, _invalid_T)

End If
If (_out_of_range = 0).During(10)
    If (_out_of_range_T <> 0) Then
        ParameterValid(GW, True,T-_valid*RATE)
        _out_of_range_T = 0
    End If
End If
If (_out_of_range > 0)
    If (_out_of_range_T = 0)
        _out_of_range_T = T
    End If
    _out_of_range -= 1
End If

' -------------------------------
' Assignment of corrected variable
GW_C = _t0

'-------------------------------------------------------------------------
'Prepare next iteration by updating gliding window by shifting all samples
' p = past
_p5=_p4
_p4=_p3
_p3=_p2
_p2=_p1
_p1=_t0

